version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Use the custom Dockerfile name
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend # Adjust the volume path

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Use the custom Dockerfile name
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Adjust the volume path
